export const COMMENT_ICON = 'https://s3.amazonaws.com/temp-for-interview/design_images/misc/comment.png'
export const CROWN_ICON = 'https://s3.amazonaws.com/temp-for-interview/design_images/misc/crown.png'
export const LIKE_EMPTY_ICON = 'https://s3.amazonaws.com/temp-for-interview/design_images/misc/like-empty.png'
export const LIKE_FILLED_ICON = 'https://s3.amazonaws.com/temp-for-interview/design_images/misc/like-filled.png'
export const SHARE_ICON = 'https://s3.amazonaws.com/temp-for-interview/design_images/misc/share.png'